In [3]:
import pandas as pd
import geopandas as gpd
from shapely import wkt

df_geodat_plz = pd.read_csv("datasets/geodata_berlin_plz.csv", sep=';')

# Convert the DataFrame to a GeoDataFrame
# Assuming the geometry is stored in a column named 'geometry' as WKT (Well-Known Text)
df_geodat_plz['geometry'] = df_geodat_plz['geometry'].apply(wkt.loads)
gdf = gpd.GeoDataFrame(df_geodat_plz, geometry='geometry')

# Convert to GeoJSON
geojson = gdf.to_json()

In [69]:
import pandas as pd
import geopandas as gpd
from shapely import wkt

# Load the CSV file
df = pd.read_csv("datasets/geodata_berlin_plz.csv", sep=';')

# Convert the 'geometry' column from WKT strings to Shapely geometries
df["geometry"] = df["geometry"].apply(wkt.loads)

# Convert the DataFrame to a GeoDataFrame
gdf = gpd.GeoDataFrame(df, geometry="geometry")

# Save to GeoJSON
gdf.to_file("output.geojson", driver="GeoJSON")

print("GeoJSON file created: output.geojson")

GeoJSON file created: output.geojson

C:\Users\farel\anaconda3\Lib\site-packages\pyogrio\geopandas.py:662: UserWarning: 'crs' was not provided.  The output dataset will not have projection information defined and may not be usable in other systems.
  write(

In [59]:
df_lstat.columns

Index(['PLZ', 'Breitengrad', 'Längengrad'], dtype='object')

In [61]:
df_lstat = pd.read_excel("datasets/Ladesaeulenregister_SEP.xlsx", header=10)

# Extract relevant columns (adjust column names as needed)
# df_lstat = df_lstat[['PLZ', 'Breitengrad', 'Längengrad']]  # Replace with actual column names

# Count the number of charging stations per PLZ
lstat_counts = df_lstat.groupby('PLZ').size().reset_index(name='count')
df_lstat_2 = df_lstat[["PLZ", "Ort"]]
merged_df = pd.merge(lstat_counts, df_lstat_2, on='PLZ', how='inner')
merged_df

         PLZ  count                      Ort
0       1011      1                   Berlin
1       1036      1                   Berlin
2       1062      1                   Berlin
3       1067     60                  Dresden
4       1067     60                  Dresden
...      ...    ...                      ...
73884  99988      2  Südeichsfeld OT Diedorf
73885  99991      1          Unstrut-Hainich
73886  99994      2      Nottertal-Heilinger
73887  99994      2      Nottertal-Heilinger
73888  99996      1               Unstruttal

[73889 rows x 3 columns]

In [73]:
import pandas as pd
import geopandas as gpd

# Load the Excel file
df_lstat = pd.read_excel("datasets/Ladesaeulenregister_SEP.xlsx", header=10)

# Extract relevant columns (adjust column names as needed)
# df_lstat = df_lstat[['PLZ', 'Breitengrad', 'Längengrad']]  # Replace with actual column names

# Count the number of charging stations per PLZ
lstat_counts = df_lstat.groupby('PLZ').size().reset_index(name='count')
df_lstat_2 = df_lstat[["PLZ", "Ort"]]

# Convert PLZ columns to strings to ensure proper merge
lstat_counts['PLZ'] = lstat_counts['PLZ'].astype(str)
df_lstat_2['PLZ'] = df_lstat_2['PLZ'].astype(str)

# Merge the lstat counts with df_lstat_2
merged_df = pd.merge(lstat_counts, df_lstat_2, on='PLZ', how='inner')

# Load the GeoJSON file
gdf = gpd.read_file("output.geojson")

# Convert PLZ columns to strings to ensure proper merge
gdf['PLZ'] = gdf['PLZ'].astype(str)

# Merge the GeoJSON data with the merged DataFrame
gdf = gdf.merge(merged_df, on='PLZ', how='left')

# Check the result of the merge
gdf.to_file("output.geojson", driver="GeoJSON")

print(gdf.head())

C:\Users\farel\AppData\Local\Temp\ipykernel_21588\1343536675.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lstat_2['PLZ'] = df_lstat_2['PLZ'].astype(str)

     PLZ                                           geometry  count     Ort
0  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...   28.0  Berlin
1  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...   28.0  Berlin
2  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...   28.0  Berlin
3  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...   28.0  Berlin
4  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...   28.0  Berlin

In [51]:
import pandas as pd
import geopandas as gpd
from shapely import wkt

# Load the CSV file
df = pd.read_csv("datasets/geodata_berlin_plz.csv", sep=';')
df_lstat = pd.read_excel("datasets/Ladesaeulenregister_SEP.xlsx", header=10)

# Extract relevant columns (adjust column names as needed)
df_lstat = df_lstat[['PLZ', 'Breitengrad', 'Längengrad']]  # Replace with actual column names

# Count the number of charging stations per PLZ
lstat_counts = df_lstat.groupby('PLZ').size().reset_index(name='count')
# Convert the 'geometry' column from WKT strings to Shapely geometries
df["geometry"] = df["geometry"].apply(wkt.loads)

# Convert the DataFrame to a GeoDataFrame
gdf = gpd.GeoDataFrame(df, geometry="geometry")

# Save to GeoJSON
gdf.to_file("output.geojson", driver="GeoJSON")

print("GeoJSON file created: output.geojson")

    PLZ  count
0  1011      1
1  1036      1
2  1062      1
3  1067     60
4  1068      1
     PLZ                                           geometry
0  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...
1  10117  POLYGON ((13.40031 52.5233, 13.40051 52.52216,...
2  10119  POLYGON ((13.40056 52.53639, 13.4026 52.53507,...
3  10178  POLYGON ((13.40918 52.52917, 13.41476 52.52779...
4  10179  POLYGON ((13.42827 52.51895, 13.42751 52.51775...
     PLZ                                           geometry  count
0  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...   28.0
1  10117  POLYGON ((13.40031 52.5233, 13.40051 52.52216,...   55.0
2  10119  POLYGON ((13.40056 52.53639, 13.4026 52.53507,...    7.0
3  10178  POLYGON ((13.40918 52.52917, 13.41476 52.52779...   29.0
4  10179  POLYGON ((13.42827 52.51895, 13.42751 52.51775...   39.0

In [53]:
import pandas as pd
import geopandas as gpd

# Load the Excel file
df_lstat = pd.read_excel("datasets/Ladesaeulenregister_SEP.xlsx", header=10)

# Extract relevant columns (adjust column names as needed)
df_lstat = df_lstat[['PLZ', 'Breitengrad', 'Längengrad']]  # Replace with actual column names

# Count the number of charging stations per PLZ
lstat_counts = df_lstat.groupby('PLZ').size().reset_index(name='count')

# Convert PLZ columns to strings to ensure proper merge
lstat_counts['PLZ'] = lstat_counts['PLZ'].astype(str)

# Load the GeoJSON file
gdf = gpd.read_file("output.geojson")

# Convert PLZ columns to strings to ensure proper merge
gdf['PLZ'] = gdf['PLZ'].astype(str)

# Print the first few rows of each DataFrame to inspect the data
print(lstat_counts.head())
print(gdf.head())

# Merge the GeoJSON data with the charging station counts
gdf = gdf.merge(lstat_counts, on='PLZ', how='left')

# Check the result of the merge
gdf.to_file("output.geojson", driver="GeoJSON")

    PLZ  count
0  1011      1
1  1036      1
2  1062      1
3  1067     60
4  1068      1
     PLZ                                           geometry
0  10115  POLYGON ((13.37239 52.53821, 13.3741 52.53717,...
1  10117  POLYGON ((13.40031 52.5233, 13.40051 52.52216,...
2  10119  POLYGON ((13.40056 52.53639, 13.4026 52.53507,...
3  10178  POLYGON ((13.40918 52.52917, 13.41476 52.52779...
4  10179  POLYGON ((13.42827 52.51895, 13.42751 52.51775...

In [87]:
df_lstat  = pd.read_excel("datasets/Ladesaeulenregister_SEP.xlsx", header=10)
df_lstat = df_lstat.loc[df_lstat['Ort'] == 'Berlin']
    # Extract and rename relevant columns
charging_stations = df_lstat[['Anzeigename (Karte)', 'Straße', 'Hausnummer', 'Breitengrad', 'Längengrad', "PLZ"]].dropna()

    # Combine "Straße" and "Hausnummer" into a single address string
charging_stations['Address'] = charging_stations['Straße'] + ' ' + charging_stations['Hausnummer'].astype(str)

    # Rename columns to match expected keys
charging_stations = charging_stations.rename(columns={
        'Anzeigename (Karte)': 'Name',
        'Breitengrad': 'Latitude',
        'Längengrad': 'Longitude'
    })
charging_stations['Latitude'] = charging_stations['Latitude'].str.replace(',', '.').astype(float)
charging_stations['Longitude'] = charging_stations['Longitude'].str.replace(',', '.').astype(float)

    # Filter out invalid coordinates
charging_stations = charging_stations[
        (charging_stations['Latitude'].between(-90, 90)) &
        (charging_stations['Longitude'].between(-180, 180))
    ]
    # Convert to a list of dictionaries
# charging_stations = charging_stations[['Name', 'Address', 'Latitude', 'Longitude']].to_dict('records')

In [89]:
rows_with_value = charging_stations.loc[charging_stations['PLZ'] == '13125']
rows_with_value

Empty DataFrame
Columns: [Name, Straße, Hausnummer, Latitude, Longitude, PLZ, Address]
Index: []

In [91]:
charging_stations

,Name,Straße,Hausnummer,Latitude,Longitude,PLZ,Address
28002,Berliner Stadtwerke KommunalPartner GmbH,Leipziger Platz,19,52.510055,13.377592,1011,Leipziger Platz 19
28003,TotalEnergies Charging Solutions,Storkower Str.,175,52.527420,13.457838,1036,Storkower Str. 175
28004,Berliner Stadtwerke KommunalPartner GmbH,Uhlandstr.,177,52.502775,13.325383,1062,Uhlandstr. 177
28005,Berliner Stadtwerke KommunalPartner GmbH,Soldiner Str.,63,52.560530,13.379380,1335,Soldiner Str. 63
28006,Berliner Stadtwerke KommunalPartner GmbH,Barmbecker Weg,1,52.533317,13.154536,1359,Barmbecker Weg 1
...,...,...,...,...,...,...,...
30923,E.ON Drive Infrastructure,Fritz-Wildung-Straße,26,52.483647,13.297820,14199,Fritz-Wildung-Straße 26
30924,Kaufland,Pichelswerderstr.,6,52.529900,13.213127,14597,Pichelswerderstr. 6
30928,Kaufland,Goerzallee,195,52.417221,13.286431,42329,Goerzallee 195
30929,E.ON Drive Infrastructure,Beecker Straße,51,51.484150,6.763808,47166,Beecker Straße 51
30930,E.ON Drive Infrastructure,Beecker Straße,51,51.484150,6.763808,47166,Beecker Straße 51

In [93]:
df_lstat_oi  = pd.read_excel("datasets/Ladesaeulenregister_SEP.xlsx", header=10)

,Betreiber,Anzeigename (Karte),Straße,Hausnummer,Adresszusatz,PLZ,Ort,Kreis/kreisfreie Stadt,Bundesland,Breitengrad,...,Public Key3,Steckertypen4,P4 [kW],Public Key4,Steckertypen5,P5 [kW],Public Key5,Steckertypen6,P6 [kW],Public Key6
0,Albwerk GmbH & Co. KG,Albwerk GmbH & Co. KG,Ennabeurer Weg,0,NaN,72535,Heroldstatt,Landkreis Alb-Donau-Kreis,Baden-Württemberg,"48,442398",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,smopi® - Multi Chargepoint Solution GmbH,smopi,Albstraße,15,NaN,72535,Heroldstatt,Landkreis Alb-Donau-Kreis,Baden-Württemberg,"48,449424",...,NaN,AC Typ 2 Steckdose,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,smopi® - Multi Chargepoint Solution GmbH,smopi,Albstraße,15,NaN,72535,Heroldstatt,Landkreis Alb-Donau-Kreis,Baden-Württemberg,"48,449424",...,NaN,AC Typ 2 Steckdose,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,smopi® - Multi Chargepoint Solution GmbH,smopi,Albstraße,15,NaN,72535,Heroldstatt,Landkreis Alb-Donau-Kreis,Baden-Württemberg,"48,449424",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Albwerk GmbH & Co. KG,Albwerk GmbH & Co. KG,Parkplatz Campingplatz,0,NaN,72589,Westerheim,Landkreis Alb-Donau-Kreis,Baden-Württemberg,"48,5105",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
charging_stations = df_lstat_oi[['Anzeigename (Karte)', 'Straße', 'Hausnummer', 'Breitengrad', 'Längengrad', "PLZ"]]
rows_with_value = charging_stations.loc[df_lstat_oi['PLZ'] == 13409]
rows_with_value

,Anzeigename (Karte),Straße,Hausnummer,Breitengrad,Längengrad,PLZ
30287,Berliner Stadtwerke KommunalPartner GmbH,Reginhardstr.,66A,"52,562678","13,373826",13409
30288,Berliner Stadtwerke KommunalPartner GmbH,Reginhardstr.,32,"52,560529","13,371225",13409
30289,EWE Go GmbH,Markstraße,16,"52,560701","13,364508",13409
30290,Lidl,Indira-Gandhi-Str.,101,"52,54627","13,469077",13409
30291,Lidl,Markstr.,41,"52,561926","13,365108",13409
30292,E.ON Drive Infrastructure,Pankower Allee 9,9,"52,5639","13,3658",13409
30293,Kaufland,Residenzstraße,85,"52,559116","13,373147",13409